version: '3.8'

services:
  mongodb:
    image: mongo:8.2.5
    container_name: meu-mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: projeto
      MONGO_INITDB_ROOT_PASSWORD: testeapi
  
